databases:
  default:
    DATABASE: go_monitoring_price_api
    HOST:     127.0.0.1
    PORT:     5432
    USER:     alex
    PASSWORD: 123123

system:
  DEBUG:  true
  SERVER: 127.0.0.1:8888
  SECRET_KEY:   :1LF1u'>_pngZp))R|{bQX5&qYV_bcLx3ii&z;a7,;&,2"FeOgM)lvL)yY%>Hpv
